options:
  java-type:
    type: string
    default: "jre"
    description: |
      Type of install to perform. Valid options are 'jre' or 'full'. The
      default is 'jre', which will install the OpenJDK Java Runtime Environment
      (JRE). Setting this to 'full' will install the OpenJDK Java Development
      Kit (JDK) in addition to the JRE.
  java-major:
    type: string
    default: "8"
    description: |
      Major version of Java. Defaults to 8.
